### ISSUE TITLE
problem building NotoNastaliqUrdu: is there a way to just build two weights even if they are not interpolatable (an option to fontmake?)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#352] opened 2017-09-16 15:09 UTC
==== building src/NotoNastaliqUrdu/NotoNastaliqUrdu-MM.plist ====
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Bold.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoNastaliqUrdu-Regular
INFO:fontmake.font_project:Decomposing glyphs for NotoNastaliqUrdu-Bold
INFO:fontmake.font_project:Removing overlaps for NotoNastaliqUrdu-Regular
INFO:fontmake.font_project:Removing overlaps for NotoNastaliqUrdu-Bold
INFO:fontmake.font_project:Saving OTF for NotoNastaliqUrdu-Regular
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GSUB', 'LookupIndex:', 63, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
[...]
NFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GSUB', 'LookupIndex:', 182, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Bold.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoNastaliqUrdu.designspace
INFO:mutatorMath:       Generating instance NotoNastaliqUrdu-Regular.ufo
INFO:mutatorMath:../instance_ufo/NotoNastaliqUrdu-Regular.ufo:
Errors calculating 602 glyphs: 
        Ain
        AinIni.outD11
        AinIni.outD2D
        AinIni.outD2H
        AinIni.outD2long
[...]
        uniFDFC
        uniFDFD
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoNastaliqUrdu-Regular
INFO:fontmake.font_project:Decomposing glyphs for NotoNastaliqUrdu-Bold
INFO:fontmake.font_project:Removing overlaps for NotoNastaliqUrdu-Regular
INFO:fontmake.font_project:Removing overlaps for NotoNastaliqUrdu-Bold
INFO:fontmake.font_project:Saving OTF for NotoNastaliqUrdu-Regular
INFO:fontTools.varLib:Axes:
OrderedDict([('weight', {'map': {400.0: 90.0, 700.0: 190.0}, 'name': 'weight', 'default': 400.0, 'tag': 'wght', 'maximum': 700.0, 'minimum': 400.0, 'labelname': {'en': 'Weight'}})])
INFO:fontTools.varLib:Internal master locations:
[{'weight': 90.0}, {'weight': 190.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [90.0, 90.0, 190.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': 0.0}, {'weight': 1.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib.interpolate_layout:Building interpolated font
INFO:fontTools.varLib.interpolate_layout:Loading master fonts
INFO:fontTools.varLib.interpolate_layout:Location: {'weight': 90.0}
INFO:fontTools.varLib.interpolate_layout:Internal location: {'weight': 90.0}
INFO:fontTools.varLib.interpolate_layout:Normalized location: {'weight': 0.0}
INFO:fontTools.varLib.interpolate_layout:Building interpolated tables
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/release/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 300, in save_otfs
    interpolate_layout_from, loc, finder, mapped=True)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/interpolate_layout.py", line 56, in interpolate_layout
    merger.mergeTables(font, master_fonts, ['GPOS'])
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 106, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
   mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 80, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 91, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 620, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 80, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 77, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((607, [607, 608]), 'list', '.glyphs', 'Coverage', '.Coverage', 'CursivePos', '[0]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by anthrotype** [comment] 2017-09-16 16:44
duplicate of https://github.com/googlei18n/fontmake/issues/336

**Closed by anthrotype** 2017-09-16 16:44 UTC
