### ISSUE TITLE
AutomatedTestReport: Glyph has intersecting components

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#22] opened 2016-02-16 22:52 UTC
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Of the errors listed by our test tool I mention:
Glyph has intersecting components. 407 more like this [marekjez86: this message occurs 408 times]'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment] 2016-02-17 07:41
@jamesgk any idea why this is?

**Comment by behdad** [comment] 2016-02-17 11:10
Oh I see, intersecting *components*!  I think we are fine with this.  It is perfectly legit to have such glyphs.  Some old apps might mishandle this, but we don't care.

**Comment by dougfelt** [comment] 2016-02-17 17:45
The lint report knows nothing about components.  The message output by
noto_lint says 'The glyph has intersecting outlines' and by this it means
that two segments of the path touch or intersect.  Lint skips composite
glyphs.

**Comment by behdad** [comment] 2016-02-23 06:34
> The lint report knows nothing about components.  The message output by
> noto_lint says 'The glyph has intersecting outlines' and by this it means
> that two segments of the path touch or intersect.  Lint skips composite
> glyphs.

Ok, we need to look into this then.

If this was about CFF font, then there is no composite.  So, we should have removed overlap.  James: do you remove overlap before expanding composites or after?

**Comment by jamesgk** [comment] 2016-02-23 18:04
I think when this error was reported the overlaps were removed from UFOs before conversion to CFF. Now the composites are expanded within the UFOs before overlap is removed, so I'd think this is fixed.

**Comment by marekjez86** [comment] 2016-02-23 18:40
I updated the pipeline (although it looks that it hasn't changed for several days).
I'm running it right now on all of my inputs.
Then i'll run noto-lint.py and keep you all informed.

**Comment by jamesgk** [comment] 2016-05-17 23:40
> Oh I see, intersecting components! I think we are fine with this. It is perfectly legit to have such glyphs. Some old apps might mishandle this, but we don't care.

Are you sure about this? I found that `$ hb-view NotoSansEthiopic-Regular.ttf 'ሕ'` yields the following (using fontmake output from the Ethiopic source in noto-source, where indeed uni1215 contains intersecting components). Is this something we can ignore?

![noto](https://cloud.githubusercontent.com/assets/988758/15342960/fe1e6450-1c4d-11e6-94e1-c765f4654717.png)

**Comment by behdad** [comment] 2016-05-19 18:13
> Are you sure about this? I found that $ hb-view NotoSansEthiopic-Regular.ttf 'ሕ' yields the following (using fontmake output from the Ethiopic source in noto-source, where indeed uni1215 contains intersecting components). Is this something we can ignore?
> 
> noto

That definitely looks wrong.  It looks to me that one of the components has the wrong direction.  Can you open in Glyphs and verify?  In general, we currently don't enforce or check contour directions.

**Comment by jamesgk** [comment] 2016-05-19 18:28
OK, both components are ccw but the top component "leftsingleflag" is flipped upside-down. So that must be causing the issue? Though I was under the impression it didn't matter for components (and we aren't decomposing the glyph in the TTF output).

Also just realized that this issue exists for OTF output as well. So I guess this needs to be fixed during decomposition as a start.

**Comment by behdad** [comment] 2016-05-19 18:34
Ok, my understanding is that if we don't decompose, then it wouldn't show up as a problem. (BTW, I find calling this decomposition a bit confusing)

When we do decompose, please reverse the contour if the decomposition matrix has a negative determinant.  I don't remember what such matrices are called.

**Comment by jamesgk** [comment] 2016-05-19 21:19
> Ok, my understanding is that if we don't decompose, then it wouldn't show up as a problem. (BTW, I find calling this decomposition a bit confusing)

That was also my understanding, but the result I shared earlier came from a TTF in which the glyph was not decomposed (I'm open to alternatives to calling this decomposition). TTF attached for reference.

[NotoSansEthiopic-Regular.ttf.zip](https://github.com/googlei18n/fontmake/files/273489/NotoSansEthiopic-Regular.ttf.zip)

**Comment by behdad** [comment] 2016-05-19 22:41
Ah.  Interesting.  Thanks.  cc @wernerlemberg

**Comment by marekjez86** [comment] 2016-08-29 13:10
still get the following

![e](https://cloud.githubusercontent.com/assets/13322623/18052437/3598af14-6daf-11e6-9fcb-e77bb09a9b20.png)

**Comment by xiangyexiao** [comment] 2016-12-05 20:22
the issues with the latest Phase 3 NotoSansKhmer seem to be related to this too.

[kmGXP3TTF.PDF](https://github.com/googlei18n/fontmake/files/632170/kmGXP3TTF.PDF)

This is the image taken from Adobe. Chrome doesn't have this issue.
<img width="954" alt="screen shot 2016-12-05 at 12 19 12 pm" src="https://cloud.githubusercontent.com/assets/12721521/20900897/ea407e74-bae4-11e6-94a6-4389afc0baab.png">

The odd lines are rendered with Phase 2 NotoSansKhmer. The even lines are rendered with Phase 3 NotoSansKhmer. 

Text in the first line is "មនុស្សទាំងអស់ ក ើតមកមានសេ រីភាព"

**Comment by anthrotype** [comment] 2017-07-24 16:19
@behdad @marekjez86 @xiangyexiao is this still an issue?

**Comment by marekjez86** [comment] 2017-07-24 16:45
@anthrotype : still appears to be an issue with the most recent sources (and fonts compiled with them)

![saneth-reg](https://user-images.githubusercontent.com/13322623/28534221-ca9696be-7054-11e7-9755-e6c027786f3e.jpeg)

**Comment by marekjez86** [comment] 2017-07-24 16:49
about PDF that Xiangye provided.
No problems on my Mac with viewing it with Chrome, Preview, Acrobat Reader and Acrobat.
Unable to reproduce the behavior reported by Xiangye on my Mac.

**Comment by anthrotype** [comment] 2017-07-24 17:12
Like behdad said:

> It looks to me that one of the components has the wrong direction. Can you open in Glyphs and verify? In general, we currently don't enforce or check contour directions.

we should verify that this isn't a source issue. That is, open glyphs source file, find that composite glyph, check that the contours of those two components have the correct winding direction, which should be counter-clockwise for PostScript outlines.

**Comment by anthrotype** [comment] 2017-07-24 17:14
If either components has been flipped than it's path direction would be reversed; however, in these cases fontmake already decomposes composite glyphs if any of the components have any transform applied (besides simple translation).

**Comment by anthrotype** [comment] 2017-07-24 17:19
oh and since you are at it, mind adding 

```
[wheel]
universal = 1
```

to `setup.cfg` as well?
Since file is a pure python package that works with both py2.py3, this will make it so a single wheel package is generated and can be installed on either major python versions.

**Comment by anthrotype** [comment] 2017-07-24 17:21
ops this is the wrong thread, sorry :grimacing:

**Comment by jamesgk** [comment] 2017-07-25 03:23
> If either components has been flipped than it's path direction would be
> reversed; however, in these cases fontmake already decomposes composite
> glyphs if any of the components have any transform applied (besides simple
> translation).

FYI, this was an issue with a flipped component not being decomposed.
So if what you describe is true this shouldn't be an issue anymore.

**Comment by anthrotype** [comment] 2017-07-25 18:50
@jamesgk Hey James, thanks. We miss you a lot! 😄 

I checked NotoSansEthiopic and indeed the generated TTFs have a that composite glyph comprising a flipped component (thus with wrong contour direction), so if the expectation was that fontmake would "decompose" composite glyphs containing transformed components then that is not the case here.

Oh now I see what's going on. The `decompose_glyphs` method takes a `glyph_filter` callable, which when building TTFs only triggers with glyphs containing mixed contours/components
https://github.com/googlei18n/fontmake/blob/d009282/Lib/fontmake/font_project.py#L184-L188

So in this case, where the TrueType glyph contain only components, the `_deep_copy_contours` method is skipped and the composite glyph isn't decomposed, despite one of it's components having a transform that flips its winding direction.

It seems like an easy fix, I'll do it tomorrow.

**Comment by behdad** [comment] 2017-07-26 00:13
So, this is in fact ambiguity in the OT spec.  We discussed it and I asked @twardoch to create a test font so we can test different rasterizers' behavior regarding composite glyphs and reversing transforms.

One thing is for sure: decomposing those glyphs should be done much more carefully...

**Comment by anthrotype** [comment] 2017-10-06 11:17
Closing as duplicate of #253. Let's track the issue there.

**Closed by anthrotype** 2017-10-06 11:17 UTC
