### ISSUE TITLE
relative path include in features

### ISSUE THREAD

**Issue by typoman** [googlei18n/fontmake#402] opened 2018-02-20 15:58 UTC
Following include means the 'font_xxx_features.fea' file is next to the UFO not inside the UFO dir.

`include(font_xxx_features.fea);`

But the fontmake gives following error:

```
fontTools.feaLib.error.FeatureLibError: font.ufo/features.fea:1:8: [Errno 2] No such file or directory: 'font.ufo/font_xxx_features.fea'
```

I guess I can fix it by changing the include path, but it doesn't seem that the path is incorrect. right?

**Comment by anthrotype** [comment] 2018-02-20 16:04
duplicate of https://github.com/googlei18n/fontmake/issues/157

**Closed by anthrotype** 2018-02-20 16:04 UTC
