### ISSUE TITLE
fontTools/varLib/merger.py issue (line 44) while merging GPOS to build Noto variation fonts

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#194] opened 2016-11-30 22:18 UTC
I ran this command $fontmake -g src/NotoSans-ItalicMM.glyphs -o variable and got this error message:

...
Building GX
Loading TTF masters
Axes:
{'custom': (100.0, 100.0, 100.0),
 'weight': (26.0, 90.0, 190.0),
 'width': (70.0, 100.0, 100.0)}
Master locations:
[{'custom': 100.0, 'weight': 26.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 90.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 151.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 190.0, 'width': 100.0},
 {'custom': 100.0, 'weight': 26.0, 'width': 70.0},
 {'custom': 100.0, 'weight': 90.0, 'width': 70.0},
 {'custom': 100.0, 'weight': 151.0, 'width': 70.0},
 {'custom': 100.0, 'weight': 190.0, 'width': 70.0}]
Normalized master locations:
[{'custom': 0, 'weight': -1.0, 'width': 0},
 {'custom': 0, 'weight': 0, 'width': 0},
 {'custom': 0, 'weight': 0.61, 'width': 0},
 {'custom': 0, 'weight': 1.0, 'width': 0},
 {'custom': 0, 'weight': -1.0, 'width': -1.0},
 {'custom': 0, 'weight': 0, 'width': -1.0},
 {'custom': 0, 'weight': 0.61, 'width': -1.0},
 {'custom': 0, 'weight': 1.0, 'width': -1.0}]
Building variations tables
Generating gvar
Generating HVAR
Merging OpenType Layout tables
Merging GPOS
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/__main__.py", line 109, in main
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 317, in run_from_glyphs
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 358, in run_from_designspace
  File "build/bdist.macosx-10.11-x86_64/egg/fontmake/font_project.py", line 428, in run_from_ufos
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 435, in main
    gx, model, master_ttfs = build(designspace_filename, finder)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 420, in build
    _merge_OTL(gx, model, master_fonts, axisTags, base_idx)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 315, in _merge_OTL
    merge_tables(font, merger, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 69, in merge_tables
    merger.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 46, in mergeLists
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 56, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 46, in mergeLists
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 54, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 271, in merge
    merger.mergeObjects(self, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 37, in mergeObjects
    self.mergeThings(value, values)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 58, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/xiangye/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 44, in mergeLists
    assert all(count == len(v) for v in lst), (count, [len(v) for v in lst])
AssertionError: ((3, [48, 3, 2, 2, 2, 2, 2, 3]), 'list', '.PairSet', 'PairPos', 'list', '.SubTable', 'Lookup', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

========================
See the same issue when building variable fonts for many other Noto fonts:

fontmake -g src/NotoSansSymbols2-Regular.glyphs -o variable
fontmake -g src/NotoSansArmenian-MM.glyphs -o variable
fontmake -g src/NotoSansCherokee-MM.glyphs -o variable
fontmake -g src/NotoSerif-ItalicMM.glyphs -o variable
fontmake -g src/NotoSerif-MM.glyphs -o variable
fontmake -g src/NotoSansDisplay-ItalicMM.glyphs -o variable
fontmake -g src/NotoSansGeorgian-MM.glyphs -o variable
fontmake -g src/NotoSerifThai-MM.glyphs -o variable
fontmake -g src/NotoSansDevanagari/NotoSansDevanagari-MM.glyphs --mti-source src/NotoSansDevanagari/NotoSansDevanagari-MM.plist -o variable

**Comment by jamesgk** [comment] 2016-11-30 22:20
This looks like another duplicate of https://github.com/fonttools/fonttools/issues/719

**Comment by marekjez86** [comment] 2016-12-08 23:58
https://github.com/fonttools/fonttools/issues/719

**Closed by marekjez86** 2016-12-08 23:58 UTC
Labels: font_variations
