### ISSUE TITLE
Errors calculating X glyphs is this a problem? ... if yes where?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#335] opened 2017-07-24 17:42 UTC
from the log building static fonts from https://github.com/googlei18n/noto-source/tree/master/src/NotoNastaliqUrdu

_.....
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoNastaliqUrdu-Bold.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoNastaliqUrdu.designspace
INFO:mutatorMath:       Generating instance NotoNastaliqUrdu-Regular.ufo
INFO:mutatorMath:../instance_ufo/NotoNastaliqUrdu-Regular.ufo:
Errors calculating 602 glyphs: 
        Ain
        AinIni.outD11
        AinIni.outD2D
        AinIni.outD2H
        AinIni.outD2long
        AinIni.outD5
        AinIni.outS1
        AinIni.outT3
        AinMed.inT3
        AinMed.inT3outD2D
        AinMed.inT3outD2H
        AinMed.inT3outD2Hwide
        AinMed.inT3outD5
        AinMed.inT3outT1
..._

![nasurd](https://user-images.githubusercontent.com/13322623/28536457-7f6c492e-705c-11e7-9bb0-3c506794e6d7.jpeg)

**Comment by anthrotype** [comment] 2017-07-24 17:58
That is mutatormath's way of saying that something went wrong while interpolating those glyphs.
I'd recommend having a look at the sources and ensure the glyphs are compatible for all the masters, i.e. the order of contours, the length (number of segments) of each contour, and the sequence of segment types for each contour matches across all masters.

**Comment by anthrotype** [comment] 2017-08-18 18:33
duplicate of #336

**Closed by anthrotype** 2017-08-18 18:33 UTC
