### ISSUE TITLE
Fontmake can not compile some glyph files

### ISSUE THREAD

**Issue by zjusbo** [googlei18n/fontmake#261] opened 2017-02-18 00:30 UTC
Steps to reproduce:
1. Convert ufo files in noto-source/src/NotoSansCham/ to .glyph file using glyph.app.
2. Compile the converted .glyph file.

Expected Result:
ttf, otf are generated successfully.

Actual Result:
Error in fontmake

(dev) bosong@bosong0:~/noto-source/src/NotoSansCham$ fontmake -u NotoSansCham-Regular.ufo/
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSansCham-Book
INFO:fontmake.font_project:Removing overlaps for NotoSansCham-Book
Traceback (most recent call last):
  File "/usr/local/google/home/bosong/fonttools/dev/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/__main__.py", line 183, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 435, in run_from_ufos
    ufos, remove_overlaps, mti_paths=mti_paths, **kwargs)
  File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 146, in build_otfs
    self.remove_overlaps(ufos)
  File "/usr/local/google/home/bosong/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/bosong/fontmake/Lib/fontmake/font_project.py", line 87, in remove_overlaps
    union(contours, glyph.getPointPen())
  File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 104, in union
    return _performOperation("union", contours, [], outPen)
  File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 64, in _performOperation
    subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
  File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 72, in __init__
    self.segments = _convertPointsToSegments(points)
  File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 440, in _convertPointsToSegments
    willBeReversed=willBeReversed
  File "/usr/local/google/home/bosong/fonttools/dev/local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 174, in __init__
    for pt1, pt2 in decomposeQuadraticSegment(pointCoordinates[1:]):
  File "/usr/local/google/home/bosong/fonttools/Lib/fontTools/pens/basePen.py", line 329, in decomposeQuadraticSegment
    assert n > 0
AssertionError

**Comment by anthrotype** [comment] 2017-02-18 00:43
duplicate of #260

**Closed by anthrotype** 2017-02-18 00:43 UTC
