### ISSUE TITLE
Issue with WorkSans Italic name table when building variable font

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/fontmake#479] opened 2018-11-08 11:32 UTC
Whilst generating a variable font for [Work Sans Italic](https://github.com/weiweihuanghuang/Work-Sans/blob/master/sources/WorkSans-Italic.glyphs), some nametable records have "Italic Italic".

id | string 
--- |  --- 
3 | 2.000;NONE;WorkSans-ItalicItalic 
4 | Work Sans Italic Italic 
6 | WorkSans-ItalicItalic 
17 | Italic Italic 

In the source, masters are named:

![screen shot 2018-11-08 at 11 20 53](https://user-images.githubusercontent.com/7525512/48195777-6ff0c280-e348-11e8-9635-a36091ec0b15.png)

If I remove "Italic" from the master names and use Thin, Regular, Black instead, the name table is correct.

id | string 
--- |  --- 
3 | 2.000;NONE;WorkSans-Italic
4 | Work Sans Italic
6 | WorkSans-Italic 

I personally think including "Italic" in a master name shouldn't cause this issue.

I apologise if this issue belongs to a sibling lib. I don't have the time to dig too deep on this.

I'm using the pip version of fontmake v1.8.0

cc @weiweihuanghuang

**Comment by anthrotype** [comment] 2018-11-08 11:40
thanks for the report.

back in the olden days, the name of the masters in Glyphs.app were hard-coded to set of predefined names (based on weight/width classes). E.g. if you take NotoSans-ItalicMM.glyphs in noto-source repo, it has Light, Regular, Bold, etc. masters, and the instances are Light Italic, Italic, Bold Italic, etc.

It doesn't take you much to change the master names in the soruces (also those names are not user-visible anyway), but I agree with you this could be improved.

I suspect the source of the issue is probably somewhere in glyphsLib, but I haven't digged further.

**Comment by m4rc1e** [comment] 2018-11-08 11:50
Thanks Cosimo! 

@weiweihuanghuang as temp workaround, lets rename the masters in the Italic to Thin, Regular and Black.

**Comment by moyogo** [comment] 2018-11-09 11:48
The current glyphsLib GSFontMaster.name() works mostly like that of Glyphs 2.4, both have "Thin Italic Italic" for master.name when master.customName="Thin Italic" and master.italicAngle is non-zero.

Glyphs 2.5 doesn’t behave that way and master.name is "Thin Italic" in that case.

**Comment by anthrotype** [comment] 2019-01-17 15:15
it just occurred to me that this naming issue might become a problem with fonts that have upright and italic masters in the same file.

**Comment by anthrotype** [comment] 2019-01-17 15:44
also.. why does WorkSans-Italic.glyphs has GSMaster.customName attribute set to, e.g., "Thin Italic"?

If I read https://docu.glyphsapp.com/index.html#GSFontMaster.customName

> The name of the custom interpolation dimension.
> Deprecated since version 2.5.2: Use GSFontMaster.axes instead.

I'm confused. /cc @madig @belluzj

**Comment by anthrotype** [comment] 2019-01-17 15:47
BTW, glyphsLib's GSFontMaster objects don't even have such an 'axes' attribute which is mentioned in the above link... I wonder if we might be missing something important here.

**Comment by anthrotype** [comment] 2019-01-17 17:17
this shall be fixed in the next version of glyphsLib, which we'll release shortly

**Closed** 2019-01-17 17:17 UTC

**Comment by anthrotype** [comment] 2019-01-17 17:19
ok. "shortly" is a overstatement. We still need to make fontmake aware of the "brace trick" we added down the pipeline (glyphsLib, ufo2ft, fonttools).
