### ISSUE TITLE
DeltaFormat in XPlaDevice table is supposed to be 1, 2, or 3

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#229] opened 2017-01-24 21:40 UTC
1. go to https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/variable
2. try to open any file there using the Glyphs.app ; the content cannot be opened (that's not the case for the variable fonts generated in the Glyphs.app - all of them can be opened by it)

This is either the pipeline problem or the Glyphs.app problem. Not certain which (help is needed :-)).

**Comment by brawer** [comment] 2017-01-30 18:26
FontView can open these fonts just fine, so it’s probably a Glyphs bug (or perhaps an unimplemented feature). Closing this fontmake bug since fontmake works as intended, byt @schriftgestalt fyi.

**Comment by schriftgestalt** [comment] 2017-02-01 00:17
I had a look at the files. It seems they have invalid Device tables:
```XML
	<XPlaDevice>
		<StartSize value="0"/>
		<EndSize value="1"/>
		<DeltaFormat value="32768"/>
	</XPlaDevice>
```
everywhere I looked, DeltaFormat is supposed to be 1, 2, or 3.

**Comment by marekjez86** [comment] 2017-02-01 00:28
@brawer : reopening per the above comment

**Comment by schriftgestalt** [comment] 2017-02-01 08:41
And I could not find out why ttx would not warn. There are asserts in the `read` method of the Device table...

**Comment by anthrotype** [comment] 2017-02-01 09:09
the code that defines DeltaFormat to `0x8000` is in `varLib.builder`:
https://github.com/fonttools/fonttools/blob/caa353d5dde1f8a0a0d1b80886d6e7c08aac5bc1/Lib/fontTools/varLib/builder.py#L145

that `buildVarDevTable ` function is then used in `varLib.merger` module:
https://github.com/fonttools/fonttools/blob/3717dc6549f5e4afd4b48e05577d138f3e875d9f/Lib/fontTools/varLib/merger.py#L471-L498

@behdad should know better

**Comment by anthrotype** [comment] 2017-02-01 09:14
> A format value of 0x8000 is used for the VariationIndex table, and indicates that a delta-set index is used to reference delta data in an ItemVariationStore table.

https://www.microsoft.com/typography/otspec/chapter2.htm

**Comment by schriftgestalt** [comment] 2017-02-01 09:36
That explains it. Thanks.

**Comment by behdad** [comment] 2017-02-25 18:54
> And I could not find out why ttx would not warn. There are asserts in the read method of the Device table...

Because we don't try reading DeltaValue if delta format is NOT in 1, 2, 3.  From otData.py:
```
↦       ('Device', [ 
↦       ↦       ('uint16', 'StartSize', None, None, 'Smallest size to correct-in ppem'), 
↦       ↦       ('uint16', 'EndSize', None, None, 'Largest size to correct-in ppem'), 
↦       ↦       ('uint16', 'DeltaFormat', None, None, 'Format of DeltaValue array data: 1, 2, or 3'), 
↦       ↦       ('DeltaValue', 'DeltaValue', '', 'DeltaFormat in (1,2,3)', 'Array of compressed data'), 
↦       ]), 
```
Note this part: `DeltaFormat in (1,2,3)',`.

Re asserting: fontTools is non-judgemental re what it reads.  The more asserts we add the harder it will be to inspect or fix bad fonts...

We already have https://github.com/fonttools/fonttools/issues/824 to improve this object.  There's not much else to do.

**Closed by behdad** 2017-02-25 18:54 UTC
