### ISSUE TITLE
pyclipper.ClipperException: All paths are invalid for clipping

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#161] opened 2016-10-16 09:42 UTC
I got the following while running make -B src/NotoSansDisplayItalic-MM.glyphs in noto-source

Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/**main**.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 143, in build_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.1.2+135.g4dd1e73-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(_args, *_kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 97, in remove_overlaps
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 88, in union
    return _performOperation("union", contours, [], outPen)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 54, in _performOperat
ion
    operation, subjectFillType="nonZero", clipFillType="nonZero")
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 36, in clipExecute
    pc.AddPaths(subjectContours, pyclipper.PT_SUBJECT)
  File "pyclipper/pyclipper.pyx", line 633, in pyclipper.Pyclipper.AddPaths (pyclipper/pyclipper.cpp:4341)
pyclipper.ClipperException: All paths are invalid for clipping

**Comment by marekjez86** [comment] 2016-10-16 09:47
also src/NotoSansDisplayRoman-MM.glyphs and src/NotoSansUIRoman-MM.glyphs

**Comment by anthrotype** [comment] 2016-10-16 11:01
I believe there could be open paths in some of the glyphs. Clipper library does not support merging open polygons. We should make sure that we don't pass such open paths to booleanOperations.union, and/or make booleanOperations raise a more meaningful error when that happens.

**Comment by anthrotype** [comment] 2016-10-16 19:25
Or it could be a glyph containing mixed contours/components, as the `remove_overlaps` does not raise errors when generating OTFs (in which case, it is preceded by a `decompose_glyphs`), but only when making the TTFs. I'll debug tomorrow.

**Comment by anthrotype** [comment] 2016-10-16 21:20
It's neither open paths, nor mixed contour/composite glyphs, but a "degenerate" contour that's crashing booleanOperations, which looks like a rectangle flattened into a line.

The glyph in question is: noto-source/instance_ufo/NotoSansDisplay-SemiCondensedThin.ufo/glyphs/uniA_767.glif

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="uniA767" format="2">
  <advance width="481"/>
  <unicode hex="A767"/>
  <anchor x="241" y="760" name="top"/>
  <anchor x="241" y="-232" name="bottom"/>
  <outline>
    <contour>
      <point x="141" y="-124" type="line"/>
      <point x="167" y="-124" type="line"/>
      <point x="167" y="-124" type="line"/>
      <point x="141" y="-124" type="line"/>
    </contour>
    <component base="thorn"/>
  </outline>
  <lib>
    <dict>
      <key>com.schriftgestaltung.Glyphs.lastChange</key>
      <string>2015/09/23 21:58:11</string>
      <key>com.schriftgestaltung.Glyphs.widthMetricsKey</key>
      <string>=thorn</string>
    </dict>
  </lib>
</glyph>
```

**Comment by moyogo** [comment] 2016-10-16 21:42
There’s a contour and a component. But anyway... the interpolation is broken because the contour has different starting points in different masters (bottom-left in Light, top-right in all the other masters).

**Comment by anthrotype** [comment] 2016-10-17 12:11
OK, I confirm this is has nothing to do with the glyph having both contours and components, since we only pass the contours to `booleanOperations`.

The problem is that `pyclipper`, and hence booleanOperations, simply can't handle such degenerate paths.

The reason why the OTFs could be built but not the TTFs is because for the OTFs we first `decompose_glyphs` before calling `remove_overlaps`; and `booleanOperations` (via `pyclipper.AddPaths`) was only raising when *all* the input paths were invalid. In the OTF case, the glyph `uniA767` would at least have one valid path so pyclipper did not raise, but still silently drop the invalid path (which is not nice either).

I just opened a PR for booleanOperations so the latter will raise a custom error instead of exposing `pyclipper.ClipperException`: https://github.com/typemytype/booleanOperations/pull/37

Once that's merged, `booleanOperations` will raise if _any_ input contour is invalid, so nothing gets lost.

What fontmake should do is simply catch `booleanOperations.Error`, log an error message with the failing glyph name, and let the exception propagate.
I'll send a PR for that soon.

**Comment by jamesgk** [comment] 2016-10-20 23:25
> but still silently drop the invalid path (which is not nice either).

Is dropping the path a problem? Are there any examples of invalid paths besides degenerate lines? Or is it safe to assume they can always be dropped (would want to warn anyways) with no change to the rendered glyph?

**Comment by marekjez86** [comment] 2016-10-21 00:12
![uni2066](https://cloud.githubusercontent.com/assets/13322623/19582204/91f1d3e2-96e7-11e6-95ff-fa26cbec72e4.jpg)

In the above situation we generate a stack trace; Glyphs.app successfully exports the OTF. Would it be possible to be compatible with the Glyphs.app in some way?

**Comment by anthrotype** [comment] 2016-10-21 09:44
> Are there any examples of invalid paths besides degenerate lines?

I'm not sure if there are other examples of invalid paths.

> is it safe to assume they can always be dropped?

I don't think it is. There might be cases in which those degenerate lines are an unintentional artifact of interpolation, while in other cases they may be intentional. I'd prefer that the user deals with them manually, instead of the library trying to figure out what the user's intentions are.

@marekjez86 in your example above, is the degenerate contour deleted by Glyphs.app when merging overlaps, or is ignored but still kept?
And is it an interpolation artifact, or was it put there intentionally for some reason?

The `BooleanOperationsError` exception message contains the index of the invalid contour, so maybe fontmake could handle the exception by retrying without the invalid contour until the `union` operation passes, and log a warning instead of letting the exception propagate.

But I would like to keep raising an exception in booleanOperations instead of silently dropping any contours, as it is not always clear what the user's expectations are.

/cc @typemytype

**Comment by marekjez86** [comment] 2016-10-26 21:45
BTW, please keep the error (at least for now): (i) we need to have clean sources and they will be fixed only if we stop after error (ii) look that this helps us to catch issues with interpolation (and we need to catch them and fix them). I consider "to keep or not to keep the error" issue resolved.

Although we may still have problem per @moyogo : " contour has different starting points in different masters (bottom-left in Light, top-right in all the other masters)." Keeping bug opened.

**Comment by marekjez86** [comment] 2016-10-26 21:46
assigning to behdad to deal with "the interpolation is broken because the contour has different starting points in different masters (bottom-left in Light, top-right in all the other masters)."

**Comment by behdad** [comment] 2016-12-18 07:31
I don't know what the status here is.  James, Cosimo?

**Comment by typemytype** [comment] 2016-12-18 10:33
Paths with no area are ignored now

See

**Comment by typemytype** [comment] 2016-12-18 10:34
Paths with no area are ignored now

See https://github.com/typemytype/booleanOperations/issues/41

**Comment by anthrotype** [comment] 2016-12-18 17:02
The status of this is: booleanOperations >= 0.6.4 no longer raises an exception when an input path has no area (i.e. invalid for clipping), but now silently drops it -- btw, that's what Glyphs.app "Remove Overlap" filter does as well.
So I guess you should find other ways to check the sources don't interpolate those zero-area contours.

**Closed** 2017-07-24 19:01 UTC
