### ISSUE TITLE
Compiling NotoSansArabicUI fails because of feaLib

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/fontmake#447] opened 2018-06-15 20:46 UTC
This is really a ufo2ft and/or fontTools.feaLib issue, but I'm not sure where this should be handled since it seems to rely on Glyphs-specific behavior. 

What happens is that there are non-exporting glyphs in the font that have anchors on them. These are added to the UFO, but since they are not exported the anchors should be ignored when building the GPOS. Since they are read by feaLib there are conflicts like this:

`fontTools.feaLib.error.FeatureLibError: <features>:1956:9: Glyph twodotsverticalabove-ar.small cannot be in both @MC_top and @MC_center`

This glyph is only used as a component so isn't exported, but it has some anchors on it (here it has both a 'top' and a 'center' anchor). In this particular case those anchors are totally pointless, but in many cases non-exporting glyphs might have anchors that "shine through" in Glyphs app so might be needed. But these should never be put in the GPOS for glyphs that will not export.

**Comment by anthrotype** [comment] 2018-06-18 12:08
@punchcutter slightly unrelated question: what do you expect to happen for those glyphs only used as components in other composite glyphs and which are marked as non-export? That the composite glyphs that use them will be decomposed?
If so, that's not what's happening, because the way fontmake gets rid of the glyphs that are marked as `Export: false` is using the fonttools subsetter after the font has been compiled, and the subsetter does not decompose a composite glyph when any of its components are not included in the subset; instead it automatically adds them to the subset (when doing the closure over the glyf table). I think this is a good thing, but maybe it's not what the export flag in Glyphs.app is supposed to do...
Anyway, probably a separate issue.

**Comment by punchcutter** [comment] 2018-06-18 13:14
No, “shine through” is the Glyphs term for using anchors from a component, the anchor propagation thing. I don’t know how Glyphs determines what should be propagated and what shouldn’t which is why I mention that as something to consider in a situation like this where a non exporting glyph is used as a component. 

Right, the way Glyphs handles non exporting components is to decompose them on export as far as I can tell. But the problem I see in this particular situation is that a glyph set to `Export: false` should never ever have its anchors written out to GPOS. It’s not being exported so the mark writer should ignore it. But, like you say, the way `Export: false` is handled in fontmake is not the same as Glyphs. That’s just another of the million Glyphs specific behaviors we can’t, or maybe don’t want to, mimic exactly.

**Comment by m4rc1e** [comment] 2018-06-19 10:06
Getting a similar issue here whilst trying to generate [comfortaa](https://github.com/googlefonts/comfortaa) using fontmake v1.5.1

```
fontmake 1.5.1
fontTools.feaLib.error.FeatureLibError: <features>:1455:9: Glyph tonos cannot be in both @MC_top and @MC_topleft
```

It genned fine using fontmake v1.3.0.

I'll keep digging :-). I'm guessing this has been caused by the recent efforts to support abvm, blwm feats in ufo2ft.

**Comment by anthrotype** [comment] 2018-06-19 10:07
no need to dig, the issue is the same I pointed to above:
https://github.com/googlei18n/ufo2ft/issues/259

**Comment by m4rc1e** [comment] 2018-06-19 10:15
Thank you. I'll revert to using v.1.4.0 for the time being.

**Comment by anthrotype** [comment] 2018-06-19 10:19
as I said, this is also related to googlei18n/ufo2ft#261

because that "tonos" glyph in Comfortaa should not be included in the mark feature, as it's not a Nonspacing combining mark, but it's a spacing mark. The current method is to treat as "marks" anything that contains some _ prefixed anchor. But apparently this is too "greedy", and may lead to that error, now that we are no longer creating separate lookups for each mark class.

**Comment by m4rc1e** [comment] 2018-06-19 11:04
> because that "tonos" glyph in Comfortaa should not be included in the mark feature

Eugh, Glyphsapp thinks it is one.

![screen shot 2018-06-19 at 11 57 08](https://user-images.githubusercontent.com/7525512/41593464-08df4576-73b8-11e8-9e90-77e58a326665.png)

In GlyphData.xml
```
<glyph unicode="0384" name="tonos" sortName="gr049" decompose="acutecomb" category="Mark" subCategory="Spacing" script="greek" description="GREEK TONOS" anchors="_top" />
```

Whilst it's actually a [Symbol modifier](https://www.fileformat.info/info/unicode/char/0384/index.htm)

**Comment by anthrotype** [comment] 2018-06-19 11:47
the subCategory for tonos is Spacing.
for marks to be considered as combining the subCategory must be "Nonspacing", see
https://github.com/googlei18n/glyphsLib/blob/0393173dc594b15bb06318e8a7fb4ce28959b25d/Lib/glyphsLib/builder/features.py#L139

**Comment by anthrotype** [comment] 2018-06-19 11:50
GDEF GlyphClassDef 3 is for "combining marks" only (those with 0 advance width that are positioned via GPOS mark/mkmk), not any mark glyphs
https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#glyph-class-definition-table-overview

**Closed** 2018-06-19 18:43 UTC
