### ISSUE TITLE
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 45)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#64] opened 2016-04-12 16:33 UTC
I got this error for the first time on 2016-04-08 at 17:52 but I didn't notice it. I just noticed it today looking at the font creation dates.

This happens when processing NotoSansEthiopic-MM.glyphs 
[NotoSansEthiopic-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/215481/NotoSansEthiopic-MM.glyphs.zip)

>> Removing overlaps for NotoSansEthiopicCondensed-Black
>> Saving OTF for NotoSansEthiopic-Thin
>> Saving OTF for NotoSansEthiopic-Light
>> Saving OTF for NotoSansEthiopic-Regular
>> Saving OTF for NotoSansEthiopic-Medium
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 58, in <module>
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 42, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 215, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 252, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 112, in build_otfs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 157, in save_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 91, in compile
    return writer.getAllData()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 412, in getAllData
    tableData = table.getData()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 282, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 45)

**Comment by jamesgk** [comment] 2016-04-12 17:30
Beat you to it! Duplicate of https://github.com/googlei18n/fontmake/issues/63

**Closed by jamesgk** 2016-04-12 17:30 UTC

**Comment by marekjez86** [comment] 2016-04-12 17:33
Thanks James for catching this earlier :-) I need to read open bugs and avoid duplicates.
