### ISSUE TITLE
fontmake does not assign a value in the GDEF/GlyphClassDef table for combining marks

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#316] opened 2017-05-08 18:44 UTC
using https://github.com/googlei18n/noto-source/blob/master/src/NotoSansNKo-MM.glyphs as an input to the fontmake.

running the following command to create the otf font
_fontmake  -i -g src/NotoSansNKo-MM.glyphs -o otf_

using the output of the fontmake as the input to noto_lint.py

noto_lint.py instance_otf/NotoSansNKo-Regular.otf
produces the following warnings which are NOT there when I create a font using Glyphs.app and use it as input to the noto_lint.py

W <gdef/classdef/unlisted> Glyph uni07EB (U+07EB NKO COMBINING SHORT HIGH TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07EC (U+07EC NKO COMBINING SHORT LOW TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07ED (U+07ED NKO COMBINING SHORT RISING TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07EE (U+07EE NKO COMBINING LONG DESCENDING TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07EF (U+07EF NKO COMBINING LONG HIGH TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07F0 (U+07F0 NKO COMBINING LONG LOW TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07F1 (U+07F1 NKO COMBINING LONG RISING TONE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07F2 (U+07F2 NKO COMBINING NASALIZATION MARK) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.
W <gdef/classdef/unlisted> Glyph uni07F3 (U+07F3 NKO COMBINING DOUBLE DOT ABOVE) is a combining mark, but is not assigned a value in the GDEF/GlyphClassDef table.

**Comment by punchcutter** [comment] 2017-06-23 21:12
This is because in glyphsLib/glyphdata.py `_get_unicode_category()` is using `unicodedata.ucd_3_2_0.category()` which doesn't have N'Ko. If we change this to unicodedata.category() then it will work, but there was a reason to stick with ucd_3_2_0 as @brawer wrote here: https://github.com/googlei18n/glyphsLib/issues/88

The other way to get around it is to hard code this info in the Glyphs file. The default GlyphData.xml has the correct info for these glyphs, but it's not saved into the Glyphs file. It's easy to do from inside Glyphs with a script like this:

```
names = [g.name for g in font.glyphs]
for name in names:
    glyph = font.glyphs[name]
    if not glyph.storeCategory:
        glyph.storeCategory = True
    if not glyph.storeSubCategory:
        glyph.storeSubCategory = True
    if not glyph.storeScript:
        glyph.storeScript = True
    if not glyph.storeProductionName:
        glyph.storeProductionName = True

```
I tried on this file and then glyphsLib sets the GDEF correctly.

**Comment by brawer** [comment] 2017-10-16 15:41
Actually, glyphsLib uses UCD3.2 only for “compression”: almost all entries in GlyphData can be inferred from the Unicode character data, and UCD3.2 is predictably available in all Python builds whereas later UCD versions may or may not be installed. Therefore, glyphsLib tries to infer the properties from UCD3.2, but of course there is an exception list to handle glyphs where the UCD look-up gives a different result than what is in GlyphsData.xml. In other words, using a different UCD version would make absolutely no difference for this bug. For example, glyphsLib already returns the correct result for `longlowtonecomb-nko`.

The problem is something else. Currently, glyphsLib assumes that Glyphs source files actually use the Glyphs-specific glyph names if one has defined. However, it looks like Noto N’Ko doesn’t follow the naming convention. To be more resilient, GlyphsLib should implement a work-around to handle fonts that don’t follow the Glyphs naming conventions. See https://github.com/googlei18n/glyphsLib/issues/232.

**Comment by brawer** [comment] 2017-10-16 18:11
Fixed upstream in https://github.com/googlei18n/glyphsLib/issues/232. GlyphsLib needs to cut a new release, and fontmake to pick it up.

**Comment by anthrotype** [comment] 2018-06-13 18:57
this should be fixed by now

**Closed by anthrotype** 2018-06-13 18:57 UTC
