### ISSUE TITLE
With the most recent source for Noto Khmer Fonts - Decomposed Versions I'm unable to make variable fonts

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#386] opened 2018-01-06 08:02 UTC
Noto Khmer Fonts Serif, Sans and UI behave the same. I get KeyError: u'NotoSerifKhmer-Condensed' traceback (for NotoSerifKhmer source)

> Traceback (most recent call last):
>   File "/usr/local/google/home/marekj/release/noto-source/env/bin/fontmake", line 11, in <module>
>     load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
>     project.run_from_glyphs(glyphs_path, **args)
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 376, in run_from_g
lyphs
>     glyphs_path, family_name, mti_source=mti_source)
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrap
per
>     return func(*args, **kwds)
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 79, in build_maste
r_ufos
>     self.add_mti_features_to_master_ufos(mti_source, masters)
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrap
per
>     return func(*args, **kwds)
>   File "/usr/local/google/home/marekj/release/noto-source/env/local/lib/python2.7/site-packages/fontmake/font_project.py", line 89, in add_mti_fea
tures_to_master_ufos
>     for table, path in mti_paths[key].items():
> KeyError: u'NotoSerifKhmer-Condensed'

**Comment by marekjez86** [comment] 2018-01-06 08:05
source from https://github.com/googlei18n/noto-source/tree/master/src/NotoSansKhmer , https://github.com/googlei18n/noto-source/tree/master/src/NotoSansKhmerUI and https://github.com/googlei18n/noto-source/tree/master/src/NotoSerifKhmer

**Comment by marekjez86** [comment] 2018-01-06 08:11
@anthrotype , @punchcutter : have you seen this before?

**Comment by anthrotype** [comment] 2018-01-06 10:46
I think this was fixed in GlyphsLib already.
https://github.com/googlei18n/glyphsLib/pull/301
The fix was released with GlyphsLib v2.2.0.
Are you using latest?

**Comment by marekjez86** [comment] 2018-01-06 16:53
I use build in noto-source and I performed ./build setup before building the fonts.


marekj@yol-worjdp:~/release/noto-source$ ./build setup
Requirement already up-to-date: fonttools==3.15.1 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 1))
Requirement already up-to-date: cu2qu==1.2.0 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 2))
Requirement already up-to-date: glyphsLib==1.8.0 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 3))
Requirement already up-to-date: ufo2ft==0.6.2 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 4))
Requirement already up-to-date: MutatorMath==2.0.4 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 5))
Requirement already up-to-date: defcon==0.3.4 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 6))
Requirement already up-to-date: booleanOperations==0.7.1 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 7))
Requirement already up-to-date: ufoLib>=2.1.0 in ./env/lib/python2.7/site-packages (from cu2qu==1.2.0->-r scripts/fontmake/requirements.txt (line 2))
Requirement already up-to-date: compreffor>=0.4.5 in ./env/lib/python2.7/site-packages (from ufo2ft==0.6.2->-r scripts/fontmake/requirements.txt (line 4))
Requirement already up-to-date: fontMath>=0.4.1 in ./env/lib/python2.7/site-packages (from MutatorMath==2.0.4->-r scripts/fontmake/requirements.txt (line 5))
Requirement already up-to-date: pyclipper>=1.0.5 in ./env/lib/python2.7/site-packages (from booleanOperations==0.7.1->-r scripts/fontmake/requirements.txt (line 7))
Processing ./scripts/fontmake
  Requirement already satisfied (use --upgrade to upgrade): fontmake==1.3.0 from file:///usr/local/google/home/marekj/release/noto-source/scripts/fontmake in ./env/lib/python2.7/site-packages
Requirement already satisfied: fonttools>=3.15.1 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: cu2qu>=1.2.0 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: glyphsLib>=1.8.0 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: ufo2ft>=0.6.2 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: MutatorMath>=2.0.4 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: defcon>=0.3.4 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: booleanOperations>=0.7.1 in ./env/lib/python2.7/site-packages (from fontmake==1.3.0)
Requirement already satisfied: ufoLib>=2.1.0 in ./env/lib/python2.7/site-packages (from cu2qu>=1.2.0->fontmake==1.3.0)
Requirement already satisfied: compreffor>=0.4.5 in ./env/lib/python2.7/site-packages (from ufo2ft>=0.6.2->fontmake==1.3.0)
Requirement already satisfied: fontMath>=0.4.1 in ./env/lib/python2.7/site-packages (from MutatorMath>=2.0.4->fontmake==1.3.0)
Requirement already satisfied: pyclipper>=1.0.5 in ./env/lib/python2.7/site-packages (from booleanOperations>=0.7.1->fontmake==1.3.0)

**Comment by marekjez86** [comment] 2018-01-06 16:55
It looks that I have

Requirement already up-to-date: glyphsLib==1.8.0 in ./env/lib/python2.7/site-packages (from -r scripts/fontmake/requirements.txt (line 3))

and not 2.2.0

**Comment by punchcutter** [comment] 2018-01-07 22:25
@marekjez86 Sorry, looks like I messed up the plist files because of the glyphsLib regression. fontmake was failing for me so I changed the plist to add "Regular" on the end of the Condensed versions to test. Then I filed the glyphsLib bug to get that fixed, but forgot to revert my local plist change before sending it over. You can see that "Regular" got added to the names here: https://github.com/googlei18n/noto-source/commit/88c7c4de1c1341b7242ec275ff034e0c71cc068c
So those plist files need to remove that mistake and then you should be able to generate fine.

**Comment by anthrotype** [comment] 2018-02-19 15:13
noto-source issue, fixed with https://github.com/fonttools/fonttools/commit/a07a6f85f72d88f533f4c82c5c6732e50aa08581

**Comment by anthrotype** [comment] 2018-02-19 15:14
sorry... pasted the wrong url :(
This is the one
https://github.com/googlei18n/noto-source/commit/0b3311dd5045880564773151cdba162fa728c74c

**Closed by anthrotype** 2018-02-19 15:13 UTC
