### ISSUE TITLE
question about NotoSerif: Is this a source or a fontmake issue?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#300] opened 2017-04-23 23:04 UTC
source: https://github.com/googlei18n/noto-source/blob/master/src/NotoSerif-MM.glyphs

Is the following stack trace a source or a fontmake issue? If source, what should I advise the provider? Note that given values  [4, 4, 4, 4, 9, 9, 9, 9] it's possible that we could subset regular width only and condensed width only and allow variation on the weight axis only (see https://github.com/googlei18n/fontmake/issues/297 ), but I'm a novice in this space :-) 

============= NotoSerif-MM.glyphs ==============
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-SemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-CondensedSemiBold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerif-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 659
2: 11368
3: 747
4: 55

INFO:fontmake.font_project:Saving TTF for NotoSerif-CondensedLight
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 5, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-Bold
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-CondensedSemiBold
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 5, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-SemiBold
INFO:fontmake.font_project:Saving TTF for NotoSerif-CondensedBold
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 5, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-Light
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-Regular
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving TTF for NotoSerif-Condensed
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 5, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Building variable font variable_ttf/NotoSerif-VF.ttf
INFO:fontTools.varLib:Internal master locations:
[{'weight': 28.0, 'width': 100.0},
 {'weight': 94.0, 'width': 100.0},
 {'weight': 152.0, 'width': 100.0},
 {'weight': 194.0, 'width': 100.0},
 {'weight': 28.0, 'width': 70.0},
 {'weight': 94.0, 'width': 70.0},
 {'weight': 152.0, 'width': 70.0},
 {'weight': 194.0, 'width': 70.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [28.0, 94.0, 194.0], 'width': [70.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0.0},
 {'weight': 0.0, 'width': 0.0},
 {'weight': 0.58, 'width': 0.0},
 {'weight': 1.0, 'width': 0.0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0.0, 'width': -1.0},
 {'weight': 0.58, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar / avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.4.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 379, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 435, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 495, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 228, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/__init__.py", line 576, in build
    _merge_OTL(vf, model, master_fonts, axisTags, base_idx)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/__init__.py", line 384, in _merge_OTL
    merger.mergeTables(font, master_fonts, axisTags, base_idx, ['GPOS'])
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 106, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 80, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 91, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 614, in merge
    merger.mergeObjects(self, lst, exclude=exclude)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/merger.py", line 97, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((4, [4, 4, 4, 4, 9, 9, 9, 9]), 'int', '.LookupType', 'Lookup', '[4]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by anthrotype** [comment] 2017-04-24 08:58
duplicate of #298

**Closed by anthrotype** 2017-04-24 08:58 UTC
