### ISSUE TITLE
Log version / hash of used libraries and sources in a table in output fonts

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#310] opened 2017-04-29 08:02 UTC
This will be very useful for debugging.  Name the table to start with an underscore perhaps, to emphasize it's not needed for the font to perform.

To make things more robust, the table can also include the list of all other tables in the font with their checksums.  So we can detect if the font was modified after build...

Just dumping ideas for now.

**Comment by behdad** [comment] 2017-07-19 01:08
This will become very handy...

**Comment by anthrotype** [comment] 2017-07-26 18:39
duplicate of #251

**Closed by anthrotype** 2017-07-26 18:39 UTC
